### ISSUE TITLE
DB User

### ISSUE THREAD

**Issue by Troglodyte13** [fhtc-cpd/render#4]
Create user table for database

**Comment by damon-e-drake** [comment]
Completed task with 
* commit: 4abc950b3bc7bf2fdb74dce2f70cf57f83657445
* file: https://github.com/fhtc-cpd/render/blob/dev/web-application/Models/Data/User.cs

User needs to be designed and updated better in the database. The initial commit is a stub user framework only. Will reissue this as another task.
